### ISSUE TITLE
Argument 1 passed to Consumer::logError() must be an instance of Throwable

### ISSUE THREAD

**Issue by numelion** [mikemadisonweb/yii2-rabbitmq#11]
```
PHP Recoverable Error 'yii\base\ErrorException' with message 'Argument 1 passed to mikemadisonweb\rabbitmq\components\Consumer::logError() must be an instance of Throwable, instance of yii\base\InvalidParamException given, called in /home/test2/www/xxx.ru/yii2/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php on line 135 and defined'

in /home/test2/www/xxx.ru/yii2/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php:289

Stack trace:
#0 /home/test2/www/xxx.ru/yii2/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php(154): mikemadisonweb\rabbitmq\components\Consumer->processMessageQueueCallback()
#1 /home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(983): mikemadisonweb\rabbitmq\components\Consumer->processMessage()
#2 /home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(983): ::call_user_func:{/home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:983}()
#3 /home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(202): PhpAmqpLib\Channel\AMQPChannel->basic_deliver()
#4 /home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(202): ::call_user_func:{/home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:202}()
#5 /home/test2/www/xxx.ru/yii2/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch()
#6 /home/test2/www/xxx.ru/yii2/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php(49): PhpAmqpLib\Channel\AbstractChannel->wait()
#7 /home/test2/www/xxx.ru/yii2/vendor/mikemadisonweb/yii2-rabbitmq/controllers/ConsumerController.php(97): mikemadisonweb\rabbitmq\components\Consumer->consume()
#8 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/InlineAction.php(57): mikemadisonweb\rabbitmq\controllers\ConsumerController->actionSingle()
#9 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#10 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams()
#11 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction()
#12 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction()
#13 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#14 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#15 /home/test2/www/xxx.ru/yii2/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest()
#16 /home/test2/www/xxx.ru/yii2/yii(20): yii\base\Application->run()
```

**Comment by mikemadisonweb** [comment]
Right, that was incompatible with PHP5. Fixed in 1.6.0.
