### ISSUE TITLE
SIGHUP results in exception in stead of restart

### ISSUE THREAD

**Issue by joorloohuis** [mikemadisonweb/yii2-rabbitmq#41]
Hi Mikhail,

I'm running into this issue where if I send a signal to one of my consumers (e.g by doing a `kill -1 <pid>`), before the the signal handler is called, I get an exception:

```
2019-02-12 18:50:56 [-][-][-][error][ErrorException:2] ErrorException: stream_select(): unable to select [4]: Interrupted system call (max_fd=3) in /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:473
Stack trace:
#0 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(474): PhpAmqpLib\Wire\IO\StreamIO->cleanup_error_handler()
#1 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(255): PhpAmqpLib\Wire\IO\StreamIO->select(3, 0)
#2 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(151): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#3 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#4 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(530): PhpAmqpLib\Wire\AMQPReader->read(7)
#5 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(578): PhpAmqpLib\Connection\AbstractConnection->wait_frame(NULL)
#6 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(227): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, NULL)
#7 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(338): PhpAmqpLib\Channel\AbstractChannel->next_frame(NULL)
#8 /app/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php(202): PhpAmqpLib\Channel\AbstractChannel->wait(NULL, false, NULL)
#9 /app/vendor/mikemadisonweb/yii2-rabbitmq/controllers/RabbitMQController.php(95): mikemadisonweb\rabbitmq\components\Consumer->consume(500)
#10 [internal function]: mikemadisonweb\rabbitmq\controllers\RabbitMQController->actionConsume('operational-sto...')
#11 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /app/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('consume', Array)
#14 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('consume', Array)
#15 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('rabbitmq/consum...', Array)
#16 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('rabbitmq/consum...', Array)
#17 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#18 /app/yii(30): yii\base\Application->run()
#19 {main}
2019-02-12 18:50:56 [-][-][-][info][mikemadisonweb\rabbitmq\components\Consumer::restartDaemon] RESTARTING
```

The last line above is the result of me adding a call to `Yii:info()` at the top of `Consumer::restartDaemon()`, just to see if it is called at all. Am I missing something in my code or configuration? It would be great to get the consumers to cleanly restart or exit based on signals I can send.

Thanks in advance.

Joor

**Comment by joorloohuis** [comment]
Sorry, forgot to mention:
php-amqplib/php-amqplib: v2.8.1
mikemadisonweb/yii2-rabbitmq: 2.0.4

**Comment by joorloohuis** [comment]
My apologies, I managed to trace this back to an issue in php-amqplib. They introduced a breaking change in v2.8.0 in the `error_handler()` in `PhpAmqpLib/Wire/IO/StreamIO.php`. They ignore errors with the string 'errno=4' (SOCKET_EINTR), but the error no longer contains the 'errno=' bit, just '[4]'.

Downgrading to v2.7.3 works around this, and SIGINT and SIGTERM are handled gracefully. SIGHUP now throws a different exception, for which I'll open a new issue.

Feel free to close this issue.

Joor

**Comment by mikemadisonweb** [comment]
Thanks for figuring this out by yourself.
